Add discovery utils to pulbot
pulibrary/pulbot pull request #95
Opened 2021-12-21 16:56 UTC by carolyncole

2021-12-27 16:55 UTC, hackartisan requested changes

2021-12-27 16:55 UTC, hackartisan commented on apps.json
> +    "repository": "pulibrary/discovery_utils",
It looks like there's not an underscore? Is it this? https://github.com/pulibrary/discoveryutils

2022-01-11 18:04 UTC, carolyncole commented on apps.json
> +    "repository": "pulibrary/discovery_utils",
Good catch!

2022-01-11 18:20 UTC, carolyncole commented
Oops discoveryutils no underscore was already in there.  I'm going to close this PR and open one just for friends.

2022-01-11 18:20 UTC, closed without merging